version: '3.8'
 
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_app_db
    ports:
      - "5433:5432"  # Map port 5432 in the container to port 5433 on the host
 
  backend:
    build:
      context: C:/Users/Hugob/OneDrive/Bureaublad/School/Software_Advanced/groep_git/luxuryproducts-backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/todo_app_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
    ports:
      - "8080:8080"
 
  frontend:
    build:
      context: C:/Users/Hugob/OneDrive/Bureaublad/School/Software_Advanced/groep_git/luxuryproducts-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"  # Serve on standard HTTP port
    depends_on:
      - backend